#+TITLE: Raiden van Bronkhorst
#+OPTIONS: toc:nil, num:nil#html-style:nil
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="styles.css" />

Software Engineer at the [[https://cdlib.org][California Digital Library]]\\
rvanbronkhorst-at-gmail-dot-com

* Areas of Interest
  - Computer Graphics
  - Natural Language Processing
  - Modelling Natural Processes

* Experience
  [[https://cdlib.org][California Digital Library]], Software Engineer, April 2022—Present\\
  - Researched and developed machine learning models for library
    related tasks
    - Entity matching for MARC records using handcrafted features
      based on string similarity.
    - Estimation of photo acquisition date
    - Accessibility metadata generation for untagged PDFs, leveraging
      pretrained document understanding models.
  - Maintained and developed for Zephir, the metadata management
    system for the [[https://hathitrust.org][HathiTrust Digital Library]].

* Hobby Projects

  - [[./lsystem/index.html][L-System Playground]] :: A simple JavaScript implemention of L-Systems.
    

  - [[https://github.com/RvanB/RomBox][RomBox]] :: A lightweight launcher for emulators and games, with
    playtime tracking.


  - [[https://github.com/cabeese/greatpuzzlehunt][The Great Puzzle Hunt]] :: The website for [[https://greatpuzzlehunt.com][The Great Puzzle Hunt]],
    an annual team-puzzling event at Western Washington University.


  - [[https://github.com/RvanB/Rock-Generator][Rock Generator]] :: One of my early explorations of computer
    graphics through software rendering. Renders "rocks" (spheres with
    noise applied) with shading, support for multiple colored lights,
    supersampling, and optimizations such as backface culling and
    multithreaded rasterization. Also calculates the volume of the
    rock with parallelepipeds.

* Education
I received my Bachelors of Science in Computer Science from [[https://wwu.edu][Western
Washington University]]. During my undergrad I worked on bioinformatics
research under [[https://facultyweb.cs.wwu.edu/~jagodzf/][Dr. Filip Jagodzinski]], and computer vision research
under [[https://facultyweb.cs.wwu.edu/~wehrwes/][Dr. Scott Wehrwein]].
